### ISSUE TITLE
Take into consideration properties on interface

### ISSUE THREAD

**Issue by ignatandrei** [jwshyns/DudNet#2]
If you add to your interface something like

```csharp
internal interface IPerson
{
    string? FirstName { get; set; }
```
this will be generated
```csharp
public partial class PersonProxy : IPerson {

	private readonly IPerson _service;

	get {
		Interceptor();
		get_NameInterceptor();
		return _service.get_Name();
	}

	set {
		Interceptor();
		set_NameInterceptor(value);
		_service.set_Name(value);
	}

}

public class PersonDud : IPerson {

	get {
		return (string) default;
	}


	set {}

```

As an example, please see branch https://github.com/ignatandrei/RSCG_Examples/tree/114-dudnet
folder : <RSCG_Examples>\v2\rscg_examples\DudNet\src\DudNet

**Comment by jwshyns** [comment]
Thanks for pointing this out, it was definitely a bit of an oversight! I'm working on a fix for this, here's a sneak peek #3 - I think it's more in line with what you would be expecting~

**Comment by ignatandrei** [comment]
Please deploy to NuGet to verify it .
Thanks
Andrei

**Comment by ignatandrei** [comment]
Did you deploy it?

**Comment by jwshyns** [comment]
Apologies - yes, it has been deployed to NuGet.

**Comment by ignatandrei** [comment]
https://ignatandrei.github.io/RSCG_Examples/v2/docs/DudNet
